fix

diff --git a/.github/workflows/build_and_push_manylinux.yml b/.github/workflows/build_and_push_manylinux.yml
--- a/.github/workflows/build_and_push_manylinux.yml
+++ b/.github/workflows/build_and_push_manylinux.yml
@@ -72,13 +72,6 @@ jobs:
           ecr: false
           logout: false
     
-      - name: Login to AscendHub
-        uses: docker/login-action@v3
-        with:
-          registry: swr.cn-north-4.myhuaweicloud.com
-          username: ${{ secrets.ASCENDHUB_USERNAME }}
-          password: ${{ secrets.ASCENDHUB_TOKEN }}
-
       - name: Build and push by digest
         uses: docker/build-push-action@v6
         id: build
@@ -86,7 +79,6 @@ jobs:
           platforms: ${{ matrix.arch }}
           tags: |
             quay.io/wxsicey/manylinux
-            swr.cn-north-4.myhuaweicloud.com/wxs_test/manylinux
           file: ${{ github.workspace }}/manylinux/${{ inputs.cann_tag }}/Dockerfile
           context: ${{ github.workspace }}/manylinux/${{ inputs.cann_tag }}
           outputs: type=image,push-by-digest=true,name-canonical=true,push=true
@@ -127,59 +119,54 @@ jobs:
           username: ${{ secrets.QUAY_USERNAME }}
           password: ${{ secrets.QUAY_TOKEN }}
 
-      - name: Login to AscendHub
-        uses: docker/login-action@v3
-        with:
-          registry: swr.cn-north-4.myhuaweicloud.com
-          username: ${{ secrets.ASCENDHUB_USERNAME }}
-          password: ${{ secrets.ASCENDHUB_TOKEN }}
-
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
       - name: Prepare tags
         id: prepare-tags
         run: |
-            BASE_TAGS=$(jq -r --arg cann_tag "${{ inputs.cann_tag }}" \
-              '.versions[] | select(.path == "manylinux/" + $cann_tag) | .tags[]' \
-              manylinux_publish_version.json)
-            registries=(
-              "quay.io/wxsicey/manylinux"
-              "swr.cn-north-4.myhuaweicloud.com/wxs_test/manylinux"
-            )
-            first=true
-            TAGS_JSON="["
-            for registry in "${registries[@]}"; do
-              for tag in $(echo "$BASE_TAGS" | tr ',' ' '); do
-                if [ "$first" != true ]; then
-                  TAGS_JSON+=","
-                fi
-                TAGS_JSON+="\"${registry}:${tag}\""
-                first=false
-              done
-            done
-            
-            TAGS_JSON+="]"
-            
-            echo "tags=${TAGS_JSON}" >> $GITHUB_OUTPUT
-
+          BASE_TAG=$(jq -r --arg cann_tag "${{ inputs.cann_tag }}" \
+            '.versions[] | select(.path == "manylinux/" + $cann_tag) | .tags[0]' \
+            manylinux_publish_version.json)
+          registry="quay.io/wxsicey/manylinux"
+          TAGS_JSON="[\"${registry}:${BASE_TAG}\"]"
+          echo "tags=${TAGS_JSON}" >> $GITHUB_OUTPUT
 
       - name: Create manifest list and push
         working-directory: ${{ runner.temp }}/digests
         env:
           TAGS: ${{ steps.prepare-tags.outputs.tags }}
         run: |
-          readarray -t TAGS_ARRAY <<< "$(echo "$TAGS" | jq -r '.[]')"
+          TAG=$(echo "$TAGS" | jq -r '.[0]')
+          if [[ "$TAG" == *"quay.io/wxsicey/manylinux"* ]]; then
+            docker buildx imagetools create -t "$TAG" \
+              $(printf 'quay.io/wxsicey/manylinux@sha256:%s ' *)
+          else
+            echo "Error: Unknown registry in TAG: $TAG"
+            exit 1
+          fi
 
-          for TAG in "${TAGS_ARRAY[@]}"; do
-            if [[ "$TAG" == *"quay.io/wxsicey/manylinux"* ]]; then
-              docker buildx imagetools create -t "$TAG" \
-                $(printf 'quay.io/wxsicey/manylinux@sha256:%s ' *)
-            elif [[ "$TAG" == *"swr.cn-north-4.myhuaweicloud.com/wxs_test/manylinux"* ]]; then
-              docker buildx imagetools create -t "$TAG" \
-                $(printf 'swr.cn-north-4.myhuaweicloud.com/wxs_test/manylinux@sha256:%s ' *)
-            else
-              echo "Error: Unknown registry in TAG: $TAG"
-              exit 1
-            fi
-          done
+  sync-image:
+    runs-on: ubuntu-latest
+    needs: push-image
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Install skopeo
+        run: |
+          sudo apt update
+          sudo apt install -y skopeo
+
+      - name: Login to Huawei Cloud SWR
+        run: |
+          echo "${{ secrets.HW_TOKEN }}" | skopeo login \
+            --username "${{ secrets.HW_USERNAME }}" \
+            --password-stdin \
+            swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci
+
+      - name: Sync image
+        run: |
+          skopeo copy --all \
+          docker://quay.io/ascend/cann:${{ inputs.cann_tag }} \
+          docker://swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/manylinux:${{ inputs.cann_tag }}
